---
- name: Include Security
  ansible.builtin.include_tasks:
    file: preinstall.yml

- name: Include Install
  ansible.builtin.include_tasks:
    file: install.yml

- name: Include PostInstall
  ansible.builtin.include_tasks:
    file: postinstall.yml
