---
- name: Init solana
  block:
    - name: Generate identity if required
      become: true
      become_user: "{{ solana_username }}"
      ansible.builtin.command: "solana-keygen new -o {{ solana_data_dir }}/identity.json --no-bip39-passphrase --silent"
      args:
        creates: "{{ solana_data_dir }}/identity.json"
      changed_when: true

    - name: Apply configuration file
      ansible.builtin.template:
        src: "startup_{{ solana_network }}.sh.j2"
        dest: "{{ solana_data_dir }}/startup.sh"
        owner: "{{ solana_username }}"
        group: "{{ solana_username }}"
        mode: "0755"

    - name: Set sysctl parameters
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        reload: true
      loop:
        - { name: net.core.rmem_default, value: "134217728" }
        - { name: net.core.rmem_max, value: "134217728" }
        - { name: net.core.wmem_default, value: "134217728" }
        - { name: net.core.wmem_max, value: "134217728" }
        - { name: vm.max_map_count, value: "1000000" }
        - { name: fs.nr_open, value: "1000000" }
        - { name: kernel.nmi_watchdog, value: "0" }
        - { name: vm.swappiness, value: "30" }

    - name: Add logrotate file
      ansible.builtin.template:
        src: logrotate.j2
        dest: /etc/logrotate.d/solana
        owner: root
        group: root
        mode: "0644"
      notify: Logrotate reload
