---
- name: Prepare
  ansible.builtin.include_tasks: prepare/main.yml

- name: Dependencies
  ansible.builtin.include_tasks: dependencies/main.yml
  when: should_init or solana_update_deps

- name: Build
  ansible.builtin.include_tasks: build/main.yml
  when: should_build | default(false)

- name: Configure
  ansible.builtin.include_tasks: configure/main.yml
  when: should_init or solana_update_config

- name: Deploy
  ansible.builtin.include_tasks: deploy/main.yml
  when: should_update or (should_build | default(false)) or should_init or solana_update_config
