---
- name: "Add service unit file"
  ansible.builtin.template:
    src: "walrusd.service.j2"
    dest: "/etc/systemd/system/{{ walrus_service_name }}"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - "Restart Walrus Service"
